---
# @see https://docs.docker.com/install/linux/docker-ce/centos/

# @see http://blog.beta-desu.info/2016/09/16/docker_apt_failed/
# @see https://qiita.com/yoshiya64/items/62d85f645499bf5b7eb6
- name: set dns
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      DNS1=8.8.8.8
      DNS2=8.8.4.4

- name: install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: set up the stable repository
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

- name: install Docker CE
  yum:
    name:
      - docker-ce-{{ docker_version }}
      - docker-ce-cli-{{ docker_cli_version }}
      - containerd.io

- name: setup Docker auto start
  service:
    name: docker
    state: started
    enabled: yes

- name: set default DNS
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- include_tasks: install_docker_compose_by_binary.yml