---
# @see http://blog.beta-desu.info/2016/09/16/docker_apt_failed/
# @see https://qiita.com/yoshiya64/items/62d85f645499bf5b7eb6
- name: set dns
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-enp0s3
    block: |
      DNS1=8.8.8.8
      DNS2=8.8.4.4

- name: install required packages
  yum:
    name: '{{ item }}'
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: set up the stable repository
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

- name: install the latest version of Docker CE
  yum:
    name: docker-ce

- name: setup Docker auto start
  service:
    name: docker
    state: started
    enabled: yes

- name: set default DNS
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: install docker, docker-compose by pip for Ansible module docker_service
  pip:
    name: '{{ item }}'
  with_items:
    - docker
    - docker-compose
